target("all_test", function ()
    add_packages("hiredis")
    add_packages("gtest")
    add_packages("toml++")
    add_deps("wrench_lib")
    set_kind("binary")
    add_includedirs("../includes")
    add_files("**.cpp")
end)
