target("wrench_deamon", function ()
    add_packages("argparse", "hiredis", "toml++", "spdlog")
    add_deps("wrench_lib")
    add_includedirs("$(projectdir)/includes")
    add_files("**.cpp")
end)
