target("wrench_deamon", function ()
    add_packages("argparse", "hiredis", "toml++", "spdlog", "fmt", "redis-plus-plus")
    add_deps("wrench_lib")
    add_includedirs("$(projectdir)/includes", "./includes")
    set_pcxxheader("includes/pch.h")
    add_files("**.cpp")
end)
